services:
  chitchat:
    build: .
    ports:
      - "443:443"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_HOST: mariadb
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      PUBLIC_DOMAIN: ${PUBLIC_DOMAIN}

  mariadb:
    image: mariadb:latest
    container_name: chitchat_mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - chitchat_sql_data:/var/data
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: chitchat_db
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

      
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

volumes:
  chitchat_sql_data:
