name: Rust CI with MariaDB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.5
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: secret
          MARIADB_USER: user
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: chitchat_db
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -ptestpass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: chitchat_db

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Wait for MariaDB to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 -ptestpass --silent; then
            echo "MariaDB is ready!"
            break
          fi
          echo "Waiting for MariaDB..."
          sleep 2
        done

    - name: Install MySQL client
      run: sudo apt-get install -y default-mysql-client

    - name: Run tests
      run: cargo test --verbose
